---
title: "Licensing"
toc: true
---

Choosing a licence is one of the most important first steps in open-sourcing a project. Without 
one, projects default to the "all rights reserved" model of copyright, where others have no
legal right to use, copy, modify, or redistribute your code, even if it is publicly visible on a 
code repository. Thus, licenses grant others certain legal rights for your code. At the same time,
they protect against malpractices or damages caused by bugs by explicitly refusing accountability.

Processes for applying a license to CERTH-developed software are presented in the 
[licensing recommendations](../recommendations/licensing.qmd) section. Here we remind that 
CERTH is the license holder of software produced during research and development activities. Yet,
the exact license must be chosen at a per-project basis, given that it must comply with the license 
of dependent software, and affects how code can be adopted externally. For example, some licenses 
disallow usage of code in non-open-source projects (see below).

Next some popular licenses are presented. These are broadly categorized in terms of permissiveness,
but compliance between licenses in the same category is not guaranteed. For example, Apache-2.0 
can be used within a more permissive BSD-3-Clause project only if Apache-2.0 requirements are 
maintained. For this reason, you may occasionally encounter mixed-licensed projects, where parts of
the codebase are governed by different licenses. That said, most projects try to stick to only one 
license for simplicity.

### Permissive licenses

Examples: [Apache-2.0](https://opensource.org/license/apache-2-0/),
[BSD-3-Clause](https://opensource.org/license/bsd-3-clause/), [MIT](https://opensource.org/license/mit/).

If you license your code under this type of licence, then anybody can reuse it, modify/combine
it with their base, and redistribute the result. They just have to respect basic
conditions, such as including your original copyright notice in the software they distribute. 

Among the freedoms you grant when you use a permissive licence is the freedom to modify your software 
without needing to distribute it as open source. That is, others (e.g. a company) can create proprietary 
products based on your code. Most academic works stick to either Apache-2.0 or MIT licenses, as they
are the easiest to reuse.

### Weakly-reciprocal licenses

Examples: [LGPL-3.0](https://opensource.org/license/lgpl-3-0/),
[LGPL-2.1](https://opensource.org/license/lgpl-2-1/), [MPL-2.0](https://opensource.org/license/mpl-2-0/).

If you license your project under this type of licence and somebody takes your source code and combines 
it with theirs, upon distribution of their code they also have to disclose yours under your license. 
This includes modifications that they made to your source code. However, they can keep their own sources 
undisclosed. This way, you can benefit from improvements to your codebase.

Keep in mind that many licenses treat code reuse and dynamic linking to compiled 
binaries differently (dynamic linking is the practice of calling external software during runtime while
only being aware of the programmatic interface when writing your programs). For example, one may release 
a proprietary program that links against an LGPL-3.0 library as long as they do not actually redistribute 
the latter themselves - their program's users need to install that separately in their system.

### Strongly-reciprocal licenses

Examples: [GPL-3.0](https://opensource.org/license/gpl-3-0/) and
[GPL-2.0](https://opensource.org/license/gpl-2-0/).

If you license your project under this type of licence and somebody distributes software that
uses your code and combines it
with theirs, they need to release the sources of both your code (modified or not) and their
code under the same license.

The vision of the creators of the GPL was to generate an ever-growing body of free
software by forcing/inviting users of your code to release theirs as well. It is thus
often referred to as a "viral" license.
