on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up conda environment
        run: |
          conda env create -f environment.yml
          conda activate ospo-certh
          echo "CONDA_DEFAULT_ENV=ospo-certh" >> "$GITHUB_ENV"
          echo "CONDA_PREFIX=$CONDA/envs/ospo-certh" >> "$GITHUB_ENV"
          echo "$CONDA/envs/ospo-certh/bin" >> "$GITHUB_PATH"

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}